// Week 3/3.4/react-message/src/App.js
import { useState } from "react";
import "./App.css";

function App() {
  const [inputMessage, setInputMessage] = useState("");
  const [displayMessage, setDisplayMessage] = useState("Hello World");

  function handleDisplayMessage() {
    setDisplayMessage(inputMessage);
  }

  return (
    <div className="container">
      <h1>React Message Display</h1>

      <label htmlFor="messageInput">Message to Display</label>

      <input
        id="messageInput"
        type="text"
        value={inputMessage}
        onChange={(event) => setInputMessage(event.target.value)}
      />

      <button onClick={handleDisplayMessage}>
        Display Message
      </button>

      <h2>{displayMessage}</h2>
    </div>
  );
}

export default App;

// Week 3/3.4/angular-message/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  message = "Hello World";

  displayMessage(newMessage: string) {
    this.message = newMessage;
  }
}

<div class="container">
  <h1>Angular Message Display</h1>

  <label for="messageInput">Message to Display</label>

  <input
    id="messageInput"
    type="text"
    #messageInput />

  <button (click)="displayMessage(messageInput.value)">
    Display Message
  </button>

  <h2>{{ message }}</h2>
</div>
